version: '3'
services:
  meu-servico:
    image: nome-da-imagem
    ports:
      - "80:80"
      - "8080:8080"
    extra_hosts:
      - "nome-do-host:endereco-ip-da-sua-maquina-local"
  meu-servico-resolver:
    image: alpine
    command: ash -c "echo 'endereco-ip-da-sua-maquina-local nome-do-host' >> /etc/hosts && sleep 999d"
