version: '3'
services:
  meu-servico:
    image: nome-da-imagem
    ports:
      - "80:80"
      - "8080:8080"
    extra_hosts:
      - "nome-do-host:${HOST_IP}"

HOST_IP=$(python -c "import socket; print(socket.gethostbyname('host.docker.internal'))")
